services:
  # --- Serviço Python (Machine Learning) ---
  # Esse JÁ VAI FUNCIONAR AGORA.
  ml-api:
    build:
      context: ./ml/model_api
      dockerfile: Dockerfile
    container_name: ml_api_container
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s # Dá um tempinho extra para o boot frio do Python

  # --- Serviço Java (Backend Spring) ---
  # PREVISTO: Se der tempo de criar o Dockerfile no Java,
  # ---------------------------------------------
  # api-backend:
  #   build:
  #     context: ./api-backend
  #     dockerfile: Dockerfile
  #   container_name: backend_java_container
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - ML_API_URL=http://ml-api:8000
  #   depends_on:
  #     ml-api:
  #       condition: service_healthy
  #   networks:
  #     - app-network

# Rede interna
networks:
  app-network:
    driver: bridge