[pytest]
# O ponto (.) diz: "A raiz do projeto é aqui onde este arquivo está".
# Isso permite que os testes façam 'from model_api.app import ...'
pythonpath = .

# Onde o pytest vai procurar os testes recursivamente
testpaths = tests

# Configurações de saída (verbose + resumo)
addopts = -v -ra --disable-warnings

# Padrões de nomes de arquivos
python_files = test_*.py